---
title: "Assignment 1: Introduction"
author: "Aileen Lavelle"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 
This exercise accompanies the introductory material in Environmental Data Analytics.

## Directions

1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex

Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.

```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex(force = TRUE)
## tIngr option sys_bin -/bin
## tImgs option repository 'https://mirrors.rit.edu/ckAN/systems/terlive/tinet'
## tImgtupdate --list
```

### Set your default knit directory

This setting will help deal with relative paths later on... - From the Tool menu, select `Global Options` - Select the RMarkdown section - In the "Evaluate chunks in directory", set the option to "Project"

## 2) Discussion Questions

Enter answers to the questions just below the \>Answer: prompt.

1.  What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took upper-level statistics in undergraduate based in R. I have used Git for a few labs, but needed a lot of hand-holding. My skills are very rusty and I am very hopeful to improve them.

2.  Are there any components of the course about which you feel confident?

> Answer: I have experience with data visualization, GLMs, and spatial analysis from my senior thesis. I taught all of these things to myself, so I am very excited to have a refresher.

3.  Are there any components of the course about which you feel apprehensive?

> Answer: I am worried about coding in general. I have struggled in the past with coding but I am very interested in gaining more confidence.

## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account.

> Answer: <https://github.com/AileenLavelle/EDA-Spring2023>

## 4) Knitting

When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai.
